=== milovan1234/IST-Kolokvijum/magacin.dtd
<!ELEMENT Magacin (Artikal+)>

<!ELEMENT Artikal (Naziv,DatumIzrade,Cena,KopmanijaProdavca,(Email+))>

<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv sifra ID #REQUIRED>

<!ELEMENT DatumIzrade (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena tip (eur|din) "din">

<!ELEMENT KopmanijaProdavca (Ime,(Adresa+))>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT Adresa (#PCDATA)>

<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email tip (privatni|sluzbeni) #REQUIRED>

=== milovan1234/IST-Kolokvijum/magacin.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">
<Magacin xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com magacin.xsd">
  <Artikal>
    <Naziv sifra="s1">Mleko</Naziv>
    <DatumIzrade>
      <Dan>15</Dan>
      <Mesec>1</Mesec>
      <Godina>2020</Godina>
    </DatumIzrade>
    <Cena tip="eur">1</Cena>
    <KopmanijaProdavca>
      <Ime>Imlek</Ime>
      <Adresa>Vojvode Stepe 120/10</Adresa>
    </KopmanijaProdavca>
    <Email tip="privatni">mlekarailekM1@gmail.com</Email>
    <Email tip="sluzbeni">imlekDOO2@gmail.com</Email>
  </Artikal>
  <Artikal>
    <Naziv sifra="s2">Plazma</Naziv>
    <DatumIzrade>
      <Dan>20</Dan>
      <Mesec>3</Mesec>
      <Godina>2020</Godina>
    </DatumIzrade>
    <Cena>120</Cena>
    <KopmanijaProdavca>
      <Ime>Bambi</Ime>
      <Adresa>Beranska 51b/3</Adresa>
      <Adresa>Kneginje Milice 26/26</Adresa>
    </KopmanijaProdavca>
    <Email tip="privatni">bambiDOO2@gmail.com</Email>
  </Artikal>
  <Artikal>
    <Naziv sifra="s3">Cips</Naziv>
    <DatumIzrade>
      <Dan>18</Dan>
      <Mesec>4</Mesec>
      <Godina>2020</Godina>
    </DatumIzrade>
    <Cena tip="din">70</Cena>
    <KopmanijaProdavca>
      <Ime>Marbo</Ime>
      <Adresa>Ustanicka 52</Adresa>
    </KopmanijaProdavca>
    <Email tip="privatni">marboM5@gmail.com</Email>
  </Artikal>
</Magacin>
